version: "3.9"

networks:
  app-network:
    driver: bridge

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: pos-server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: pos-client
    ports:
      - "80:80"
    env_file:
      - ./client/.env
    restart: always
