FROM oven/bun:latest

WORKDIR /app

COPY package.json bun.lock ./

# Copy ALL workspaces
COPY server/ ./server/
COPY client/ ./client/
COPY packages/ ./packages/

RUN bun install

# Generate Prisma client
WORKDIR /app/server
RUN bunx prisma generate

EXPOSE 3000

CMD ["bun", "run", "dev"]